/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sdaib_credit.vista;

import javax.swing.JOptionPane;
import sdaib_credit.controlador.PagoControlador;
import sdaib_credit.modelo.Credito;
import sdaib_credit.modelo.Pago;

/**
 *
 * @author User
 */
public class UIPago extends javax.swing.JPanel {
    private PagoControlador pagoControlador;
    /**
     * Creates new form UIPago
     */
    public UIPago(PagoControlador pagoControlador) {
        initComponents();
        this.pagoControlador = pagoControlador;
        
        
        
        tf_IdPago.setEnabled(false);
        tf_MontoAPagar.setEnabled(false);
        tf_Fecha.setEnabled(false);
        
        btn_RealizarPago.setEnabled(false);
        
        tf_IngrIdCredito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                evenKeyTyped(evt);
            }
        });
        tf_MontoAPagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                evenKeyTyped2(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_IngrIdCredito = new javax.swing.JTextField();
        btn_Consultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lb_MontoRestante = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_MontoAPagar = new javax.swing.JTextField();
        btn_RealizarPago = new javax.swing.JButton();
        btn_Cerrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tf_Fecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_IdPago = new javax.swing.JTextField();

        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Ingrese el id del credito:");

        tf_IngrIdCredito.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_IngrIdCredito.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tf_IngrIdCreditoCaretUpdate(evt);
            }
        });

        btn_Consultar.setText("Consultar");
        btn_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Monto restante");

        lb_MontoRestante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ingrese un monto a pagar:");

        tf_MontoAPagar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_MontoAPagar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tf_MontoAPagarCaretUpdate(evt);
            }
        });

        btn_RealizarPago.setText("Realizar Pago");
        btn_RealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RealizarPagoActionPerformed(evt);
            }
        });

        btn_Cerrar.setText("Cerrar");
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Fecha:");

        tf_Fecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_Fecha.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tf_FechaCaretUpdate(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Ingrese un id:");

        tf_IdPago.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_IdPago.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tf_IdPagoCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(460, 460, 460))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(tf_MontoAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_RealizarPago))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_MontoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(274, 274, 274))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_IngrIdCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(129, 129, 129)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_IdPago, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_Consultar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_IngrIdCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Consultar))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_MontoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_IdPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_RealizarPago)
                    .addComponent(jLabel3)
                    .addComponent(tf_MontoAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(btn_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultarActionPerformed
        // TODO add your handling code here:
        if(tf_IngrIdCredito.getText().length() < 1){
            JOptionPane.showMessageDialog(null, "Ingrese el id del credito");
            return;
        }
        Credito credito = pagoControlador.getCredito(tf_IngrIdCredito.getText());
        if(credito == null){
            JOptionPane.showMessageDialog(null, "No se ha encontrado ningun credito con id '" + tf_IngrIdCredito.getText() +"'");
            return;
        }
        lb_MontoRestante.setText(credito.getMontoActual());
        
        tf_IdPago.setEnabled(true);
        tf_MontoAPagar.setEnabled(true);
        tf_Fecha.setEnabled(true);
        
        btn_RealizarPago.setEnabled(true);
        btn_Consultar.setEnabled(false);
    }//GEN-LAST:event_btn_ConsultarActionPerformed

    private void tf_IngrIdCreditoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tf_IngrIdCreditoCaretUpdate
        pagoControlador.recibirIdCredito(tf_IngrIdCredito.getText());
        tf_IdPago.setEnabled(false);
        tf_MontoAPagar.setEnabled(false);
        tf_Fecha.setEnabled(false);
        
        btn_RealizarPago.setEnabled(false);
        btn_Consultar.setEnabled(true);
    }//GEN-LAST:event_tf_IngrIdCreditoCaretUpdate

    private void btn_RealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RealizarPagoActionPerformed
        // TODO add your handling code here:
        if(tf_IdPago.getText().length() < 1 || tf_MontoAPagar.getText().length() < 1 ||
                tf_Fecha.getText().length() < 1){
            JOptionPane.showMessageDialog(null, "Campos sin llenar");
            return;
        }
        Pago pago = pagoControlador.getPago(tf_IdPago.getText());
        if(pago != null){
            JOptionPane.showMessageDialog(null, "Ya existe un pago con id '" + tf_IdPago.getText() +"'");
            return;
        }
        Credito credito = pagoControlador.getCredito(tf_IngrIdCredito.getText());
        Float montoAPagar = Float.valueOf(tf_MontoAPagar.getText());
        Float montoFaltante = Float.valueOf(credito.getMontoActual());
        if(montoAPagar == 0){
            JOptionPane.showMessageDialog(null, "El monto a pagar debe ser mayor a 0");
            return;
        }
        if(montoAPagar > montoFaltante){
            JOptionPane.showMessageDialog(null, "El monto ingresado excede el monto faltante del credito");
            return;
        }
        
        boolean pagoCorrectamente = pagoControlador.realizarPago();
        if(pagoCorrectamente){
            JOptionPane.showMessageDialog(null, "Se ha realizado el pago exitosamente");
        }else{
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error durante el pago");
        }
        credito = pagoControlador.getCredito(tf_IngrIdCredito.getText());
        lb_MontoRestante.setText(credito.getMontoActual());
        
        tf_IdPago.setText("");
        tf_MontoAPagar.setText("");
        tf_Fecha.setText("");
        
    }//GEN-LAST:event_btn_RealizarPagoActionPerformed

    private void tf_IdPagoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tf_IdPagoCaretUpdate
        pagoControlador.recibirIdPago(tf_IdPago.getText());
    }//GEN-LAST:event_tf_IdPagoCaretUpdate

    private void tf_MontoAPagarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tf_MontoAPagarCaretUpdate
        pagoControlador.recibirMontoAPagar(tf_MontoAPagar.getText());
    }//GEN-LAST:event_tf_MontoAPagarCaretUpdate

    private void tf_FechaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tf_FechaCaretUpdate
        pagoControlador.recibirFecha(tf_Fecha.getText());
    }//GEN-LAST:event_tf_FechaCaretUpdate

    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
        // TODO add your handling code here:
        pagoControlador.cerrar();
    }//GEN-LAST:event_btn_CerrarActionPerformed

    private void evenKeyTyped(java.awt.event.KeyEvent evt) {                                          
        if(!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') &&
                evt.getKeyCode() != 8 && evt.getKeyCode() != 127){
            evt.consume();
        }
    }
    private void evenKeyTyped2(java.awt.event.KeyEvent evt) {                                          
        if(!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') &&
                evt.getKeyCode() != 8 && evt.getKeyCode() != 127 &&
                evt.getKeyChar() != '.'){
            evt.consume();
        }
        if(evt.getKeyChar() == '.' && tf_MontoAPagar.getText().contains(".")){
            evt.consume();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JButton btn_Consultar;
    private javax.swing.JButton btn_RealizarPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lb_MontoRestante;
    private javax.swing.JTextField tf_Fecha;
    private javax.swing.JTextField tf_IdPago;
    private javax.swing.JTextField tf_IngrIdCredito;
    private javax.swing.JTextField tf_MontoAPagar;
    // End of variables declaration//GEN-END:variables
}
