/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sdaib_credit.vista;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sdaib_credit.controlador.UIUsuarioAsesorControlador;
import sdaib_credit.controlador.UIVerActInfClienteControlador;
import sdaib_credit.modelo.Cliente;
import sdaib_credit.modelo.Credito;

/**
 *
 * @author User
 */
public class UIVerActInfClientes extends javax.swing.JPanel {
    private UIVerActInfClienteControlador uIVerActInfClienteControlador;
    private UIUsuarioAsesorControlador uIUsuarioAsesorControlador;
    private Cliente cliente;
    /**
     * Creates new form UIVerActInfClientes
     */
    public UIVerActInfClientes(UIVerActInfClienteControlador uIVerActInfClienteControlador) {
        initComponents();
        this.uIVerActInfClienteControlador = uIVerActInfClienteControlador;
        
        jLabel2.setEnabled(false);
        jLabel3.setEnabled(false);
        jLabel4.setEnabled(false);
        tb_Creditos.setEnabled(false);
        tf_Identificacion.setEnabled(false);
        tf_Identificacion.setEditable(false);
        tf_Nombre.setEnabled(false);
        tf_Nombre.setEditable(false);
        
        btn_EditarIformacion.setEnabled(false);
        btn_GuardarCambios.setEnabled(false);
        btn_Cancelar.setEnabled(false);
        
        tf_Identificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                evenKeyTyped(evt);
            }
        });
        tf_IngresarId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                evenKeyTyped(evt);
            }
        });
        tb_Creditos.removeAll();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Tipo");
        modelo.addColumn("Pagado");
        tb_Creditos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_IngresarId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Creditos = new javax.swing.JTable();
        btn_EditarIformacion = new javax.swing.JButton();
        btn_GuardarCambios = new javax.swing.JButton();
        btn_Cerrar = new javax.swing.JButton();
        tf_Identificacion = new javax.swing.JTextField();
        tf_Nombre = new javax.swing.JTextField();
        btn_Cancelar = new javax.swing.JButton();

        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Ingrese la identificacion del cliente:");

        tf_IngresarId.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tf_IngresarIdCaretUpdate(evt);
            }
        });

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Creditos");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Identificacion:");

        tb_Creditos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_Creditos);

        btn_EditarIformacion.setText("Editar informacion");
        btn_EditarIformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarIformacionActionPerformed(evt);
            }
        });

        btn_GuardarCambios.setText("Guardar cambios");
        btn_GuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarCambiosActionPerformed(evt);
            }
        });

        btn_Cerrar.setText("Cerrar");
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_IngresarId, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_EditarIformacion, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(btn_GuardarCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_IngresarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btn_EditarIformacion)
                        .addGap(18, 18, 18)
                        .addComponent(btn_GuardarCambios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Cerrar)
                        .addGap(28, 28, 28)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(tf_IngresarId.getText().length()<1){
            JOptionPane.showMessageDialog(null, "Debe ingresar la identificacion del cliente");
            return;
        }
        cliente = uIVerActInfClienteControlador.iDAOClientes.getRegistro(tf_IngresarId.getText());
        if(cliente == null){
            JOptionPane.showMessageDialog(null, "La persona con identificaion '" + tf_IngresarId.getText() + "' "
                    + "no es cliente el banco");
            return;
        }
        tf_Identificacion.setText(cliente.getIdentificacion());
        tf_Nombre.setText(cliente.getNombre());
        List<Credito> creditos = new ArrayList<>();
        for(int i = 0; i<cliente.getCreditos().size(); i++){
            creditos.add(uIVerActInfClienteControlador.iDaoCreditos.getRegistro(cliente.getCreditos().get(i)));
        }
        cargarListCreditos(creditos);
        jLabel2.setEnabled(true);
        jLabel3.setEnabled(true);
        jLabel4.setEnabled(true);
        tb_Creditos.setEnabled(true);
        tf_Identificacion.setEnabled(true);
        tf_Nombre.setEnabled(true);
        
        btn_EditarIformacion.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_EditarIformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarIformacionActionPerformed
        btn_EditarIformacion.setEnabled(false);
        btn_GuardarCambios.setEnabled(true);
        btn_Cancelar.setEnabled(true);
        tf_Nombre.setEditable(true);
    }//GEN-LAST:event_btn_EditarIformacionActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        tf_Nombre.setText(cliente.getNombre());
        tf_Nombre.setEditable(false);
        btn_Cancelar.setEnabled(false);
        btn_GuardarCambios.setEnabled(false);
        btn_EditarIformacion.setEnabled(true);
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_GuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarCambiosActionPerformed
        if(tf_Identificacion.getText().length() < 1 || tf_Nombre.getText().length() < 1){
            JOptionPane.showMessageDialog(null, "Hay campos vacios");
            return;
        }
        Cliente clt = new Cliente(tf_Nombre.getText(), tf_Identificacion.getText());
        for(int i = 0; i < cliente.getCreditos().size(); i++){
            clt.addCredito(cliente.getCreditos().get(i));
        }
        cliente = clt;
        uIVerActInfClienteControlador.iDAOClientes.actualizarRegistro(cliente);
        JOptionPane.showMessageDialog(null, "Se ha actualizado la informacion correctamente");
        btn_EditarIformacion.setEnabled(true);
        btn_GuardarCambios.setEnabled(false);
        btn_Cancelar.setEnabled(false);
        tf_Identificacion.setEditable(false);
        tf_Nombre.setEditable(false);
    }//GEN-LAST:event_btn_GuardarCambiosActionPerformed

    private void tf_IngresarIdCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tf_IngresarIdCaretUpdate
        jLabel2.setEnabled(false);
        jLabel3.setEnabled(false);
        jLabel4.setEnabled(false);
        tb_Creditos.setEnabled(false);
        tf_Identificacion.setEnabled(false);
        tf_Nombre.setEnabled(false);
        
        btn_EditarIformacion.setEnabled(false);
        btn_GuardarCambios.setEnabled(false);
        btn_Cancelar.setEnabled(false);
    }//GEN-LAST:event_tf_IngresarIdCaretUpdate

    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
        uIUsuarioAsesorControlador = new UIUsuarioAsesorControlador();
    }//GEN-LAST:event_btn_CerrarActionPerformed

    private void cargarListCreditos(List<Credito> creditos){
        tb_Creditos.removeAll();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Tipo");
        modelo.addColumn("Pagado");
        tb_Creditos.setModel(modelo);
        
        for(int i = 0; i < creditos.size(); i++){
            Credito cred = creditos.get(i);
            String[] str = new String[3];
            str[0] = cred.getId();
            str[1] = cred.getTipoCredito();
            str[2] = "NO";
            if(cred.isPagado()) str[2] = "SI";
            modelo.addRow(str);
        }
        
    }
    
    private void evenKeyTyped(java.awt.event.KeyEvent evt) {                                          
        if(!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') &&
                evt.getKeyCode() != 8 && evt.getKeyCode() != 127){
            evt.consume();
        }
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JButton btn_EditarIformacion;
    private javax.swing.JButton btn_GuardarCambios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_Creditos;
    private javax.swing.JTextField tf_Identificacion;
    private javax.swing.JTextField tf_IngresarId;
    private javax.swing.JTextField tf_Nombre;
    // End of variables declaration//GEN-END:variables
}
